name: Sanity Test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 pytest

      - name: Auto-format with Black
        run: |
          source .venv/bin/activate
          echo "## Code Formatting (Black)" > report.md
          black --check --diff src/ tests/ >> report.md 2>&1 || echo "Black formatting issues found" >> report.md
          echo "" >> report.md

      - name: Lint with Flake8
        run: |
          source .venv/bin/activate
          echo "## Linting Results (Flake8)" >> report.md
          flake8 src/ tests/ --max-line-length=88 --extend-ignore=E203,W503 >> report.md 2>&1 || echo "Linting issues found" >> report.md
          echo "" >> report.md

      - name: Train the model
        run: |
          source .venv/bin/activate
          python src/train.py

      - name: Run unit tests
        run: |
          source .venv/bin/activate
          echo "## Test Results" >> report.md
          pytest tests/ --tb=short --disable-warnings >> report.md 2>&1 || echo "Some tests failed" >> report.md
          echo "" >> report.md

      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Comment report using CML
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source .venv/bin/activate
          cml comment create report.md
